// Copyright 2022 liangzhuzhi2020@gmail.com, https://github.com/liang-zhu-zi/esp32-thingsboard-mqtt-client
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// ThingsBoard Client MQTT helper (TBCMH) API

#ifndef _TBC_MQTT_HELPER_H_
#define _TBC_MQTT_HELPER_H_

#include <stdint.h>
#include <stdbool.h>

#include "cJSON.h"

#include "tbc_utils.h"
#include "tbc_transport_config.h"

#ifdef __cplusplus
extern "C" {
#endif

//====0.tbcm client====================================================================================================
#define TBCMH_FUNCTION_TIMESERIES_DATA      0x00000001
#define TBCMH_FUNCTION_ATTRIBUTES_REQUEST   0x00000002
#define TBCMH_FUNCTION_ATTRIBUTES_UPDATE    0x00000004
#define TBCMH_FUNCTION_ATTRIBUTES_SUBSCRIBE 0x00000008
#define TBCMH_FUNCTION_SERVER_RPC           0x00000010
#define TBCMH_FUNCTION_CLIENT_RPC           0x00000020
#define TBCMH_FUNCTION_CLAIMING_DEVICE      0x00000040
#define TBCMH_FUNCTION_OTA_UPDATE           0x00000080

#define TBCMH_FUNCTION_DEVICE_PROVISION     0x00001000

#define TBCMH_FUNCTION_FULL_ATTRIBUTES      (TBCMH_FUNCTION_ATTRIBUTES_REQUEST | \
                                             TBCMH_FUNCTION_ATTRIBUTES_UPDATE  | \
                                             TBCMH_FUNCTION_ATTRIBUTES_SUBSCRIBE) //0x0000000E

#define TBCMH_FUNCTION_FULL_OTA_UPDATE      (TBCMH_FUNCTION_TIMESERIES_DATA    | \
                                             TBCMH_FUNCTION_ATTRIBUTES_REQUEST | \
                                             TBCMH_FUNCTION_ATTRIBUTES_SUBSCRIBE  | \
                                             TBCMH_FUNCTION_OTA_UPDATE)        //0x0000008B

#define TBCMH_FUNCTION_FULL_GENERAL         (TBCMH_FUNCTION_TIMESERIES_DATA    | \
                                             TBCMH_FUNCTION_ATTRIBUTES_REQUEST | \
                                             TBCMH_FUNCTION_ATTRIBUTES_UPDATE  | \
                                             TBCMH_FUNCTION_ATTRIBUTES_SUBSCRIBE  | \
                                             TBCMH_FUNCTION_SERVER_RPC         | \
                                             TBCMH_FUNCTION_CLIENT_RPC         | \
                                             TBCMH_FUNCTION_CLAIMING_DEVICE    | \
                                             TBCMH_FUNCTION_OTA_UPDATE)        // 0x000000FF

/**
 * ThingsBoard MQTT Client Helper handle
 */
typedef struct tbcmh_client *tbcmh_handle_t;

/**
 * ThingsBoard MQTT Client Helper value, for example: data point, attributes
 */
typedef cJSON tbcmh_value_t;

/**
 * ThingsBoard MQTT Client Helper rpc params
 */
typedef cJSON tbcmh_rpc_params_t;

/**
 * ThingsBoard MQTT Client Helper rpc results
 */
typedef cJSON tbcmh_rpc_results_t;
  
/**
 * ThingsBoard MQTT Client Helper provision params
 */
typedef cJSON tbcmh_provision_params_t;

/**
 * ThingsBoard MQTT Client Helper provision results
 */
typedef cJSON tbcmh_provision_results_t;

typedef enum tbc_provison_type
{
  TBC_PROVISION_TYPE_NONE = 0,
  TBC_PROVISION_TYPE_SERVER_GENERATES_CREDENTIALS,             // Credentials generated by the ThingsBoard server
  TBC_PROVISION_TYPE_DEVICE_SUPPLIES_ACCESS_TOKEN,             // Devices supplies Access Token
  TBC_PROVISION_TYPE_DEVICE_SUPPLIES_BASIC_MQTT_CREDENTIALS,   // Devices supplies Basic MQTT Credentials
  TBC_PROVISION_TYPE_DEVICE_SUPPLIES_X509_CREDENTIALS          // Devices supplies X.509 Certificate
} tbc_provison_type_t;

/*
 | Provisioning request  | Parameter              | Description                                                                    | Credentials generated by <br/>the ThingsBoard server | Devices supplies<br/>Access Token | Devices supplies<br/>Basic MQTT Credentials | Devices supplies<br/>X.509 Certificate |
 |-----------------------|------------------------|--------------------------------------------------------------------------------|------------------------------------------------------|-----------------------------------|---------------------------------------------|----------------------------------------|
 |                       | deviceName             | Device name in ThingsBoard.                                                    | (O) DEVICE_NAME                                      | (O) DEVICE_NAME                   | (O) DEVICE_NAME                             | (O) DEVICE_NAME                        |
 |                       | provisionDeviceKey     | Provisioning device key, you should take it from configured device profile.    | (M) PUT_PROVISION_KEY_HERE                           | (M) PUT_PROVISION_KEY_HERE        | (M) PUT_PROVISION_KEY_HERE                  | (M) PUT_PROVISION_KEY_HERE             |
 |                       | provisionDeviceSecret  | Provisioning device secret, you should take it from configured device profile. | (M) PUT_PROVISION_SECRET_HERE                        | (M) PUT_PROVISION_SECRET_HERE     | (M) PUT_PROVISION_SECRET_HERE               | (M) PUT_PROVISION_SECRET_HERE          |
 |                       | credentialsType        | Credentials type parameter.                                                    |                                                      | (M) ACCESS_TOKEN                  | (M) MQTT_BASIC                              | (M) X509_CERTIFICATE                   |
 |                       | token                  | Access token for device in ThingsBoard.                                        |                                                      | (M) DEVICE_ACCESS_TOKEN           |                                             |                                        |
 |                       | clientId               | Client id for device in ThingsBoard.                                           |                                                      |                                   | (M) DEVICE_CLIENT_ID_HERE                   |                                        |
 |                       | username               | Username for device in ThingsBoard.                                            |                                                      |                                   | (M) DEVICE_USERNAME_HERE                    |                                        |
 |                       | password               | Password for device in ThingsBoard.                                            |                                                      |                                   | (M) DEVICE_PASSWORD_HERE                    |                                        |
 |                       | hash                   | Public key X509 hash for device in ThingsBoard.                                |                                                      |                                   |                                             | (M) MIIB……..AQAB                       |
 |                       | (O) Optional, (M) Must |
 */
typedef struct tbc_provison_config
{
  tbc_provison_type_t provisionType; // Generates/Supplies credentials type. // Hardcode or device profile.
 
  const char *deviceName;           // Device name in TB        // Chip name + Chip id, e.g., "esp32-C8:D6:93:12:BC:01". Each device is different.
  const char *provisionDeviceKey;   // Provision device key     // Hardcode or device profile. Each model is different. 
  const char *provisionDeviceSecret;// Provision device secret  // Hardcode or device profile. Each model is different.

  const char *token;     // Access token for device             // Randomly generated. Each device is different.
  const char *clientId;  // Client id for device                // Randomly generated. Each device is different.
  const char *username;  // Username for device                 // Randomly generated. Each device is different.
  const char *password;  // Password for device                 // Randomly generated. Each device is different.
  const char *hash;      // Public key X509 hash for device     // Public key X509.    Each device is different.
} tbc_provison_config_t;

/**
 * ThingsBoard MQTT Client Helper OTA update type
 */
typedef enum
{
  TBCMH_OTAUPDATE_TYPE_FW = 0, /*!< F/W OTA update */
  TBCMH_OTAUPDATE_TYPE_SW      /*!< S/W OTA update */
} tbcmh_otaupdate_type_t;

/**
 * @brief  Callback of connected ThingsBoard IoT Platform
 *
 * Notes:
 * - If you call tbcmh_connect(), this callback function will be called
 *   when ThingsBoard IoT Platform is connected
 * - In this callback function: Subsribe shared attributes update or server-side RPC, send attribues request and ... 
 *
 * @param client    ThingsBoard MQTT Client Helper handle. client param of tbcmh_connect()
 * @param context   context param
 *
 */
typedef void (*tbcmh_on_connected_t)(tbcmh_handle_t client, void *context);

/**
 * @brief  Callback of disconnected ThingsBoard IoT Platform
 *
 * Notes:
 * - If you call tbcmh_connect(), this callback function will be called
 *   when ThingsBoard IoT Platform is disconnected
 * - In this callback function: ... 
 *
 * @param client    ThingsBoard MQTT Client Helper handle. client param of tbcmh_connect()
 * @param context   context param
 *
 */
typedef void (*tbcmh_on_disconnected_t)(tbcmh_handle_t client, void *context);

//====1.telemetry time-series data=====================================================================================
//====2.client-side attribute==========================================================================================
//====3.subscriebe shared attributes update ===============================================================================

/**
 * @brief  Callback function when shared attributes update is received 
 * from ThingsBoard IoT platform
 *
 * Notes:
 * - If you call tbcmh_attributes_subscribe() or tbcmh_attributes_subscribe_of_array(), 
 *   this callback function will be called when you receive shared attributes updates 
 * - Parse and deal received json object in this callback function
 *
 * @param client    ThingsBoard MQTT Client Helper handle. client param of tbcmh_attributes_subscribe()
 *                    or tbcmh_attributes_subscribe_of_array()
 * @param context   context param
 * @param object    shared attributes updated, possibly contains multiple shared attributes
 *
 * @return 2 if tbcmh_disconnect() or tbcmh_destroy() is called inside in this callback function
 *         1 if tbcmh_sharedattributes_unregister() or tbcmh_attributes_unsubscribe() 
 *              is called inside in this callback function
 *         0 on otherwise
 */ // TODO: remove retrn-value-1
typedef int  (*tbcmh_attributes_on_update_t)(tbcmh_handle_t client,
                                         void *context, const cJSON *object);

//====4.attributes request for client-side_attributes & shared attributes ================================================
/**
 * @brief  Callback function when client-side_attributes & shared attributes response is received 
 * from ThingsBoard IoT platform
 *
 * Notes:
 * - If you call tbcmh_attributes_request(), tbcmh_clientattributes_request() 
 *   or tbcmh_sharedattributes_request(), this callback function will be called
 *   when you receive client-side_attributes & shared attributes response
 * - Parse and deal received json object in this callback function
 *
 * @param client            ThingsBoard MQTT Client Helper handle. client param of tbcmh_attributes_request()
 *                              or tbcmh_clientattributes_request() or tbcmh_sharedattributes_request()
 * @param context           context param 
 * @param client_attributes client-side attributes response, possibly contains multiple client-side attributes
 * @param shared_attributes shared attributes response, possibly contains multiple shared attributes
 *
 * @return 2 if tbcmh_disconnect() or tbcmh_destroy() is called inside in this callback function
 *         1 if tbcmh_sharedattributes_unregister() or tbcmh_attributes_unsubscribe() 
 *              is called inside in this callback function
 *         0 on otherwise
 */ // TODO: remove retrn-value-1
typedef void (*tbcmh_attributes_on_response_t)(tbcmh_handle_t client,
                                         void *context,
                                         const cJSON *client_attributes,
                                         const cJSON *shared_attributes);

/**
 * @brief  Callback function when client-side_attributes & shared attributes response is timeout 
 * from ThingsBoard IoT platform
 *
 * Notes:
 * - When you call tbcmh_attributes_request(), tbcmh_clientattributes_request() 
 *   or tbcmh_sharedattributes_request(), this callback function will be called
 *   when client-side_attributes & shared attributes response is timeout
 * - Parse and deal timeout evennt in this callback function
 *
 * @param client    ThingsBoard MQTT Client Helper handle. client param of tbcmh_attributes_request()
 *                      or tbcmh_clientattributes_request() or tbcmh_sharedattributes_request()
 * @param context   context param 
 *
 * @return 2            if tbcmh_disconnect() or tbcmh_destroy() is called inside in this callback function
 *         0/ESP_OK     on success
 *         -1/ESP_FAIL  on failure
 */
typedef int (*tbcmh_attributes_on_timeout_t)(tbcmh_handle_t client,
                                        void *context);

//====5.Server-side RPC================================================================================================

/**
 * @brief  Callback function when server-side RPC is received from ThingsBoard IoT platform
 *
 * Notes:
 * - If you call tbcmh_serverrpc_subscribe(), this callback function will be called
 *   when you receive server-side RPC 
 * - Parse and deal received rpc_params in this callback function
 *
 * @param client     ThingsBoard MQTT Client Helper handle. client param of tbcmh_serverrpc_subscribe()
 * @param context    context param
 * @param request_id 
 * @param method     rpc method name
 * @param rpc_params rpc params
 *
 * @return NULL if it is one-way server-side RPC without response.
 *              It MUST returns NULL if calling tbcmh_disconnect() or tbcmh_destroy() inside it!
 *         A rpc_results (cJSON object) if it is two-way server-side RPC with response,
 *              Free rpc_results by caller/(this library)
 */
typedef tbcmh_rpc_results_t *(*tbcmh_serverrpc_on_request_t)(tbcmh_handle_t client,
                                void *context, uint32_t request_id,
                                const char *method, const tbcmh_rpc_params_t *rpc_params);

//====6.Client-side RPC================================================================================================
/**
 * @brief  Callback function when two-way client-side RPC response is received 
 * from ThingsBoard IoT platform
 *
 * Notes:
 * - If you call tbcmh_twoway_clientrpc_request(), this callback function will be called
 *   when you receive client-side RPC response
 * - Parse and deal received rpc_results in this callback function
 *
 * @param client    ThingsBoard MQTT Client Helper handle. client param of 
 *                      tbcmh_twoway_clientrpc_request()
 * @param context   context param 
 * @param method     rpc method name
 * @param results    rpc results in client-side RPC response
 *
 * @return 2 if tbcmh_disconnect() or tbcmh_destroy() is called inside in this callback function
 *         1 if tbcmh_sharedattributes_unregister() or tbcmh_attributes_unsubscribe() 
 *              is called inside in this callback function
 *         0 on otherwise
 */
typedef void (*tbcmh_clientrpc_on_response_t)(tbcmh_handle_t client,
                                void *context,
                                const char *method, const tbcmh_rpc_results_t *results);

/**
 * @brief  Callback function when two-way client-side RPC response is timeout 
 * from ThingsBoard IoT platform
 *
 * Notes:
 * - If you call tbcmh_twoway_clientrpc_request(), this callback function will be called
 *   when  client-side RPC response is timeout
 * - Parse and deal timeout event in this callback function
 *
 * @param client    ThingsBoard MQTT Client Helper handle. client param of 
 *                      tbcmh_twoway_clientrpc_request()
 * @param context   context param 
 * @param method    rpc method name
 *
 * @return 2 if tbcmh_disconnect() or tbcmh_destroy() is called inside in this callback function
 *         0/ESP_OK on success
 *         -1/ESP_FAIL on failure
 */
typedef int (*tbcmh_clientrpc_on_timeout_t)(tbcmh_handle_t client,
                                void *context,
                                const char *method);

//====7.Claiming device using device-side key scenario============================================

//====8.Device provisioning=======================================================================

/**
 * @brief  Callback function when provision response is received 
 * from ThingsBoard IoT platform
 *
 * Notes:
 * - If you call tbcmh_deviceprovision_request(), this callback function will be called
 *   when you receive provision response
 * - Parse and deal received credentials in this callback function
 *
 * @param client        ThingsBoard MQTT Client Helper handle. client param of 
 *                          tbcmh_deviceprovision_request()
 * @param context       context param 
 * @param credentials   it in received provision response
 *
 */
typedef void (*tbcmh_provision_on_response_t)(tbcmh_handle_t client,
                                void *context,
                                const tbc_transport_credentials_config_t *credentials);

/**
 * @brief  Callback function when provision response is timeout 
 * from ThingsBoard IoT platform
 *
 * Notes:
 * - If you call tbcmh_deviceprovision_request(), this callback function will be called
 *   when provision response is timeout
 * - Parse and deal timeout event in this callback function
 *
 * @param client        ThingsBoard MQTT Client Helper handle. client param of 
 *                          tbcmh_deviceprovision_request()
 * @param context       context param 
 * @param credentials   it in received provision response
 *
 * @return 2 if tbcmh_disconnect() or tbcmh_destroy() is called inside in this callback function
 *         0/ESP_OK on success
 *         -1/ESP_FAIL on failure
 *
 */
typedef int (*tbcmh_provision_on_timeout_t)(tbcmh_handle_t client, void *context);

//====9.Firmware/Software update=======================================================================================

/**
 * @brief  Callback function of get current F/W or S/W title
 *
 * Notes:
 * - If you call tbcmh_otaupdate_subscribe(), this callback function will be called
 *   before sending F/W or S/W shared attributes request
 * - Don't call TBCMH API in this callback!
 *
 * @param context       context param of tbcmh_otaupdate_subscribe()
 * @param credentials   it in received provision response
 *
 */
typedef const char* (*tbcmh_otaupdate_on_get_current_title_t)(void *context);

/**
 * @brief  Callback function of get current F/W or S/W version
 *
 * Notes:
 * - If you call tbcmh_otaupdate_subscribe(), this callback function will be called
 *   before sending F/W or S/W shared attributes request
 * - Don't call TBCMH API in this callback!
 *
 * @param context       context param of tbcmh_otaupdate_subscribe()
 * @param credentials   it in received provision response
 *
 */
typedef const char* (*tbcmh_otaupdate_on_get_current_version_t)(void *context);

/**
 * @brief  Callback function if F/W or S/W upgrade completed or aborted
 *
 * Notes:
 * - If you call tbcmh_otaupdate_subscribe(), this callback function will be called
 *   after F/W or S/W upgrade completed or aborted
 * - Don't call TBCMH API in this callback!
 *
 * @param context   context param of tbcmh_otaupdate_subscribe()
 * @param result    true: upgrade successful, false: updated failed
 *
 */
typedef void (*tbcmh_otaupdate_on_updated_t)(void *context, bool result);

//====0.tbcm client====================================================================================================
tbcmh_handle_t tbcmh_init();
void tbcmh_destroy(tbcmh_handle_t client);
bool tbcmh_connect_using_url(tbcmh_handle_t client,
                                const tbc_transport_config_esay_t *config,
                                uint32_t function, void *context,
                                tbcmh_on_connected_t on_connected,
                                tbcmh_on_disconnected_t on_disconnected);
bool tbcmh_connect(tbcmh_handle_t client,
                                const tbc_transport_config_t *config,
                                uint32_t function, void *context,
                                tbcmh_on_connected_t on_connected,
                                tbcmh_on_disconnected_t on_disconnected);
void tbcmh_disconnect(tbcmh_handle_t client);
bool tbcmh_is_connected(tbcmh_handle_t client);
bool tbcmh_has_events(tbcmh_handle_t client);
void tbcmh_run(tbcmh_handle_t client); // loop()/checkTimeout, recv/parse/sendqueue/ack...

//====10.Publish Telemetry time-series data==============================================================================
int tbcmh_telemetry_upload(tbcmh_handle_t client, const char *telemetry,
                            int qos/*= 1*/, int retain/*= 0*/);
int tbcmh_telemetry_upload_ex(tbcmh_handle_t client, tbcmh_value_t *object,
                              int qos/*= 1*/, int retain/*= 0*/);

//====20.Publish client-side device attributes to the server============================================================
int tbcmh_attributes_update(tbcmh_handle_t client, const char *attributes,
                                 int qos /*= 1*/, int retain /*= 0*/);
int tbcmh_attributes_update_ex(tbcmh_handle_t client, tbcmh_value_t *object,
                                    int qos/*= 1*/, int retain/*= 0*/);

//====21.Subscribe to shared device attribute updates from the server===================================================
tbc_err_t tbcmh_attributes_subscribe(tbcmh_handle_t client,
                                        void *context,
                                        tbcmh_attributes_on_update_t on_update,
                                        int count, /*const char *key,*/...);
tbc_err_t tbcmh_attributes_subscribe_of_array(tbcmh_handle_t client, //int qos /*=0*/,
                                        void *context,
                                        tbcmh_attributes_on_update_t on_update,
                                        int count, const char *key[]);
tbc_err_t tbcmh_attributes_unsubscribe(tbcmh_handle_t client,
                                        int attributes_subscribe_id);

//====22.Request client-side or shared device attributes from the server================================================
//return 0/ESP_OK on successful, otherwise return -1/ESP_FAIL
tbc_err_t tbcmh_attributes_request(tbcmh_handle_t client,
                                 void *context,
                                 tbcmh_attributes_on_response_t on_response,
                                 tbcmh_attributes_on_timeout_t on_timeout,
                                 const char *client_keys, const char *shared_keys);
tbc_err_t tbcmh_clientattributes_request(tbcmh_handle_t client,
                                 void *context,
                                 tbcmh_attributes_on_response_t on_response,
                                 tbcmh_attributes_on_timeout_t on_timeout,
                                 int count, /*const char *key,*/...);
tbc_err_t tbcmh_sharedattributes_request(tbcmh_handle_t client,
                                 void *context,
                                 tbcmh_attributes_on_response_t on_response,
                                 tbcmh_attributes_on_timeout_t on_timeout,
                                 int count, /*const char *key,*/...);

//====30.Server-side RPC================================================================================================
//Call it before tbcmh_connect()
//return 0/ESP_OK on successful, otherwise return -1/ESP_FAIL
tbc_err_t tbcmh_serverrpc_subscribe(tbcmh_handle_t client,
                                const char *method, void *context,
                                tbcmh_serverrpc_on_request_t on_request);
//remove from LIST_ENTRY(tbcmh_serverrpc_) & delete
//return 0/ESP_OK on successful, otherwise return -1/ESP_FAIL
tbc_err_t tbcmh_serverrpc_unsubscribe(tbcmh_handle_t client, const char *method);

//====31.Client-side RPC================================================================================================
// free `params` by caller/(user code)!
//return 0/ESP_OK on successful, otherwise return -1/ESP_FAIL
tbc_err_t tbcmh_oneway_clientrpc_request(tbcmh_handle_t client,
                                const char *method, /*const*/ tbcmh_rpc_params_t *params);

// free `params` by caller/(user code)!
// create to add to LIST_ENTRY(tbcmh_clientrpc_)
//return 0/ESP_OK on successful, otherwise return -1/ESP_FAIL
tbc_err_t tbcmh_twoway_clientrpc_request(tbcmh_handle_t client,
                                const char *method, /*const*/ tbcmh_rpc_params_t *params,
                                void *context,
                                tbcmh_clientrpc_on_response_t on_response,
                                tbcmh_clientrpc_on_timeout_t on_timeout);

//====40.Claiming device using device-side key scenario============================================
tbc_err_t tbcmh_claiming_device_using_device_side_key(tbcmh_handle_t client,
                                const char *secret_key, uint32_t *duration_ms);

//====50.Device provisioning=======================================================================
//return 0/ESP_OK on successful, otherwise return -1/ESP_FAIL
tbc_err_t tbcmh_deviceprovision_request(tbcmh_handle_t client,
                                const tbc_provison_config_t *config,
                                void *context,
                                tbcmh_provision_on_response_t on_response,
                                tbcmh_provision_on_timeout_t on_timeout);

//====60.Firmware update================================================================================================
// Call it before tbcmh_connect()
tbc_err_t tbcmh_otaupdate_subscribe(tbcmh_handle_t client, 
                const char *ota_description,  // TODO: remove it!
                tbcmh_otaupdate_type_t ota_type,
                void *context_user,
                tbcmh_otaupdate_on_get_current_title_t on_get_current_title,
                tbcmh_otaupdate_on_get_current_version_t on_get_current_version,
                tbcmh_otaupdate_on_updated_t on_updated);
tbc_err_t tbcmh_otaupdate_unsubscribe(tbcmh_handle_t client, const char *ota_description);

#ifdef __cplusplus
}
#endif //__cplusplus

#endif
