#
# Component Makefile
#

COMPONENT_ADD_INCLUDEDIRS := include

COMPONENT_PRIV_INCLUDEDIRS := private_include
COMPONENT_PRIV_INCLUDEDIRS += src/transport
COMPONENT_PRIV_INCLUDEDIRS += src/mqtt

COMPONENT_SRCDIRS := src/transport
COMPONENT_SRCDIRS += src/mqtt

ifdef CONFIG_TB_MQTT_CLIENT_HELPER_ENABLE
    COMPONENT_PRIV_INCLUDEDIRS += src/helper

    COMPONENT_SRCDIRS += src/helper
endif
