#
# Component Makefile
#

COMPONENT_ADD_INCLUDEDIRS := include
COMPONENT_PRIV_INCLUDEDIRS := private_include
COMPONENT_SRCDIRS := src
ifdef CONFIG_TB_MQTT_CLIENT_HELPER_ENABLE
    COMPONENT_SRCDIRS += src/helper
endif
