#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#
PROJECT_NAME := basic_mqtt_credential_up_wo_ssl

EXTRA_COMPONENT_DIRS = $(IDF_PATH)/examples/common_components/protocol_examples_common  ../../../components/tbcmh

include $(IDF_PATH)/make/project.mk
