#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#
PROJECT_NAME := dev_sup_basic_mqtt_credential_cup_w_onewayssl

EXTRA_COMPONENT_DIRS = $(IDF_PATH)/examples/common_components/protocol_examples_common  ../../../components/tbcmh

include $(IDF_PATH)/make/project.mk
